import { loader } from "fumadocs-core/source";
// `.source` is generated by fumadocs-mdx at the web root (outside `src`),
// so it is imported relatively rather than via the `@/` alias.
import { docs } from "../../.source/server";

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
